name: Python Semantic Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"
    
    - name: Install dependencies and run tests with coverage
      run: |
        poetry install --only=main,test
        poetry run pytest

  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    needs: [ test ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: Build Python package
    #   run: poetry build
    
    # - name: Create Github semantic release
    #   uses: cycjimmy/semantic-release-action@v3
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     semantic_version: 18

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package distributions to GitHub Releases
      id: github-release
      if: steps.release.outputs.released == 'true'
      uses: python-semantic-release/upload-to-gh-release@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}