name: Python Semantic Release

on:
  push:
    branches:
      - main

jobs:
  test:
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"
    - name: Install dependencies and run tests with coverage
      run: |
        poetry install --only=main,test
        poetry run pytest

  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
    contents: write  # to create GitHub Releases
    needs: test

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}