name: Python Semantic Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"
    
    - name: Install dependencies and run tests with coverage
      run: |
        poetry install --only=main,test
        poetry run pytest

  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    needs: [ test ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Create Github semantic release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic   # Need an `id` for output variables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 18

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"

    - name: Build Python package
      run: poetry build

    - name: Upload package to just created release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: dist/*
        tag: ${{ steps.semantic.outputs.new_release_git_tag }}
